name: pgenet
favicon: null
layout_spectrum: 0.52697
typography_spectrum: 0.4193548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#230f0a'
    - '#fffeff'
    - '#893200'
    - '#fcc28e'
    - '#e26b30'
  brandStrength: 0.7939068
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
