name: pgenet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4193548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#414042'
    - '#0C0B0C'
    - '#FFB44D'
    - '#B5AB90'
  brandStrength: 0.7939068
  lightness: 0.5878136
  saturation: 1
  rhythmicContrast: 0.6505376
purpose: []
