layout_spectrum: 1
typography_spectrum: 0.4193548
color:
  saturation: 0.6971326
  lightness: 0.5878136
  brandStrength: 0.7939068
  brandColors:
    - '#FFFFFF'
    - '#414042'
    - '#0C0B0C'
    - '#FFB44D'
    - '#B5AB90'
  rhythmicContrast: 0.6505376
name: pgenet
